# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_signals.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_signals.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x63ontrol_signals.proto\".\n\x0cStartRequest\x12\x0c\n\x04port\x18\x01 \x01(\r\x12\x10\n\x08\x63hannels\x18\x02 \x01(\r\"\x1b\n\x0bStopRequest\x12\x0c\n\x04port\x18\x01 \x01(\r\"!\n\x11SampleRateRequest\x12\x0c\n\x04rate\x18\x01 \x01(\r\"j\n\x12SensitivityRequest\x12,\n\x07voltage\x18\x01 \x01(\x0e\x32\x1b.SensitivityRequest.Voltage\"&\n\x07Voltage\x12\x08\n\x04\x46IVE\x10\x00\x12\x07\n\x03TEN\x10\x01\x12\x08\n\x04VREF\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SENSITIVITYREQUEST_VOLTAGE = _descriptor.EnumDescriptor(
  name='Voltage',
  full_name='SensitivityRequest.Voltage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VREF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=205,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_SENSITIVITYREQUEST_VOLTAGE)


_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='StartRequest.port', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='StartRequest.channels', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=71,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='StopRequest.port', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=100,
)


_SAMPLERATEREQUEST = _descriptor.Descriptor(
  name='SampleRateRequest',
  full_name='SampleRateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate', full_name='SampleRateRequest.rate', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=135,
)


_SENSITIVITYREQUEST = _descriptor.Descriptor(
  name='SensitivityRequest',
  full_name='SensitivityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voltage', full_name='SensitivityRequest.voltage', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSITIVITYREQUEST_VOLTAGE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=243,
)

_SENSITIVITYREQUEST.fields_by_name['voltage'].enum_type = _SENSITIVITYREQUEST_VOLTAGE
_SENSITIVITYREQUEST_VOLTAGE.containing_type = _SENSITIVITYREQUEST
DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['SampleRateRequest'] = _SAMPLERATEREQUEST
DESCRIPTOR.message_types_by_name['SensitivityRequest'] = _SENSITIVITYREQUEST

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTREQUEST,
  __module__ = 'control_signals_pb2'
  # @@protoc_insertion_point(class_scope:StartRequest)
  ))
_sym_db.RegisterMessage(StartRequest)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPREQUEST,
  __module__ = 'control_signals_pb2'
  # @@protoc_insertion_point(class_scope:StopRequest)
  ))
_sym_db.RegisterMessage(StopRequest)

SampleRateRequest = _reflection.GeneratedProtocolMessageType('SampleRateRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLERATEREQUEST,
  __module__ = 'control_signals_pb2'
  # @@protoc_insertion_point(class_scope:SampleRateRequest)
  ))
_sym_db.RegisterMessage(SampleRateRequest)

SensitivityRequest = _reflection.GeneratedProtocolMessageType('SensitivityRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENSITIVITYREQUEST,
  __module__ = 'control_signals_pb2'
  # @@protoc_insertion_point(class_scope:SensitivityRequest)
  ))
_sym_db.RegisterMessage(SensitivityRequest)


# @@protoc_insertion_point(module_scope)
